TEST-13 Add RN.txt

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -3,7 +3,7 @@ name: android-staging-automation
 on:
   push:
     branches: 
-    - 'xxxx'
+    - test-13
 
 jobs:
   android-staging-automation:
@@ -14,103 +14,118 @@ jobs:
     env: 
       FIREBASE_APP_DIST: ${{ secrets.FIREBASE_APP_DIST }}
     steps:
-    - id: slack-start-notif
-      uses: slackapi/slack-github-action@v1.23.0
-      with:
-        channel-id: "C047A336X0X"
-        payload: |
-          {
-            "text": "[DEV-Android] Semongko App Release",
-            "attachments": [
-              {
-                "pretext": "GitHub Action STARTED",
-                "color": "dbab09",
-                "fields": [
-                  {
-                    "title": "App Release Status",
-                    "short": true,
-                    "value": "Semongko app release to Firebase App Distribution in Progress"
-                  }
-                ]
-              }
-            ]
-          }
-      env:
-        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}
+    # - id: slack-start-notif
+    #   uses: slackapi/slack-github-action@v1.23.0
+    #   with:
+    #     channel-id: "C047A336X0X"
+    #     payload: |
+    #       {
+    #         "text": "[DEV-Android] Semongko App Release",
+    #         "attachments": [
+    #           {
+    #             "pretext": "GitHub Action STARTED",
+    #             "color": "dbab09",
+    #             "fields": [
+    #               {
+    #                 "title": "App Release Status",
+    #                 "short": true,
+    #                 "value": "Semongko app release to Firebase App Distribution in Progress"
+    #               }
+    #             ]
+    #           }
+    #         ]
+    #       }
+    #   env:
+    #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}
     - name: checkout source code
       uses: actions/checkout@v3
-    - name: Limits Heap Out
+    - name: Update Release Notes
       run: |
-        export NODE_OPTIONS=--max_old_space_size=4096
-        export GOOGLE_APPLICATION_CREDENTIALS=/home/runner/work/fastlane-semongko/fastlane-semongko/android/semongko.json
-    - name: Use Node.js ${{ matrix.node-version }}
-      uses: actions/setup-node@v3
-      with:
-        node-version: ${{ matrix.node-version }}
-        cache: 'yarn'
-    - name: Setup JDK 11
-      uses: actions/setup-java@v3
-      with:
-        distribution: 'zulu'
-        java-version: '11'
-        cache: 'gradle'
-    - name: Install depedencies
-      run: |
-        yarn install
-        sudo gem install bundler
-    - name: Install Fastlane
-      run: |
-        cd android
-        bundle install
-    # - name: Instal Fastlane Plugins
+        touch release_notes.txt
+        echo "$(git show -s --format=%s)" >> release_notes.txt
+    # - name: Limits Heap Out
+    #   run: |
+    #     export NODE_OPTIONS=--max_old_space_size=4096
+    #     export GOOGLE_APPLICATION_CREDENTIALS=/home/runner/work/fastlane-semongko/fastlane-semongko/android/semongko.json
+    # - name: Use Node.js ${{ matrix.node-version }}
+    #   uses: actions/setup-node@v3
+    #   with:
+    #     node-version: ${{ matrix.node-version }}
+    #     cache: 'yarn'
+    # - name: Setup JDK 11
+    #   uses: actions/setup-java@v3
+    #   with:
+    #     distribution: 'zulu'
+    #     java-version: '11'
+    #     cache: 'gradle'
+    # - name: Install depedencies
+    #   run: |
+    #     yarn install
+    #     sudo gem install bundler
+    # - name: Install Fastlane
     #   run: |
     #     cd android
-    #     fastlane add_plugin firebase_app_distribution
-    - name: Fastlane Beta
-      env:
-        NODE_OPTIONS: "--max_old_space_size=4096"
-      run: |
-        cd android
-        fastlane beta  
-    - uses: actions/upload-artifact@v3
+    #     bundle install
+    # # - name: Instal Fastlane Plugins
+    # #   run: |
+    # #     cd android
+    # #     fastlane add_plugin firebase_app_distribution
+    # - name: Fastlane Beta
+    #   env:
+    #     NODE_OPTIONS: "--max_old_space_size=4096"
+    #   run: |
+    #     cd android
+    #     fastlane beta  
+    # - uses: actions/upload-artifact@v3
+    #   with:
+    #     name: apk-manifest
+    #     path: android/app/build/outputs/apk/release/
+    # - id: slack-finish-notif
+    #   uses: slackapi/slack-github-action@v1.23.0
+    #   with:
+    #     # The following message update step does not accept a channel name.
+    #     # Setting a channel ID here for consistency is highly recommended.
+    #     channel-id: "C047A336X0X"
+    #     payload: |
+    #       {
+    #         "text": "[DEV-Android] Semongko App Release",
+    #         "attachments": [
+    #           {
+    #             "pretext": "GitHub Action FINISHED",
+    #             "color": "dbab09",
+    #             "fields": [
+    #               {
+    #                 "title": "App Release Status",
+    #                 "short": true,
+    #                 "value": "Semongko app release to Firebase App Distribution Uploaded"
+    #               }
+    #             ]
+    #           }
+    #         ]
+    #       }
+    #   env:
+    #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}
+    # - name: Post Result to a Slack channel
+    #   if: success() || failure()
+    #   id: slack-manifest
+    #   uses: slackapi/slack-github-action@v1.23.0
+    #   with:
+    #     # Slack channel id, channel name, or user id to post message.
+    #     # See also: https://api.slack.com/methods/chat.postMessage#channels
+    #     # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
+    #     channel-id: 'C047A336X0X'
+    #     # For posting a simple plain text message
+    #     slack-message: "[DEV-Android] Semongko App Release result:  ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
+    #   env:
+    #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
+    - name: Upload APK to Slack
+      uses: MeilCli/slack-upload-file@v3
       with:
-        name: apk-manifest
-        path: android/app/build/outputs/apk/release/
-    - id: slack-finish-notif
-      uses: slackapi/slack-github-action@v1.23.0
-      with:
-        # The following message update step does not accept a channel name.
-        # Setting a channel ID here for consistency is highly recommended.
-        channel-id: "C047A336X0X"
-        payload: |
-          {
-            "text": "[DEV-Android] Semongko App Release",
-            "attachments": [
-              {
-                "pretext": "GitHub Action FINISHED",
-                "color": "dbab09",
-                "fields": [
-                  {
-                    "title": "App Release Status",
-                    "short": true,
-                    "value": "Semongko app release to Firebase App Distribution Uploaded"
-                  }
-                ]
-              }
-            ]
-          }
-      env:
-        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}
-    - name: Post Result to a Slack channel
-      if: success() || failure()
-      id: slack-manifest
-      uses: slackapi/slack-github-action@v1.23.0
-      with:
-        # Slack channel id, channel name, or user id to post message.
-        # See also: https://api.slack.com/methods/chat.postMessage#channels
-        # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
-        channel-id: 'C047A336X0X'
-        # For posting a simple plain text message
-        slack-message: "[DEV-Android] Semongko App Release result:  ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
-      env:
-        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
+        slack_token: ${{ secrets.SLACK_BOT_TOKEN }}
+        channel_id: C047A336X0X
+        file_path: 'release_notes.txt'
+        content: 'file'
+        file_type: 'txt'
+        file_name: 'release_notes.txt'
+        title: 'qa apk file'
+        initial_comment: 'Uploaded by GitHub Action'
